kind: pipeline
type: docker
name: default

concurrency:
  limit: 1

steps:

- name: Install dependencies
  image: jonrlow/ubuntu-gatsby-netlify
  commands:
  - yarn
  - gatsby build

- name: Gatsby Build
  image: jonrlow/ubuntu-gatsby-netlify
  commands:
  - gatsby build

- name: Deploy to Netlify
  image: jonrlow/ubuntu-gatsby-netlify
  commands:
  - netlify deploy --prod --dir=public --functions=functions --message="${DRONE_BRANCH}@${DRONE_COMMIT_SHA:0:7} - ${DRONE_COMMIT_MESSAGE}"
  environment:
    NETLIFY_AUTH_TOKEN:
      from_secret: NETLIFY_AUTH_TOKEN
    NETLIFY_SITE_ID: 6b5b50c1-964c-4b75-93f2-d18c2c260947


trigger:
  branch:
  - master